-- Insert news articles
INSERT INTO public.news_articles (id, title, title_arabic, excerpt, content, category, author, author_bio, date, read_time, likes, comments) VALUES
(1,
 'Grand Mosque Renovation Project Announced',
 'الإعلان عن مشروع تجديد المسجد الكبير',
 'We are excited to announce the commencement of the Grand Mosque renovation project, bringing modern facilities while preserving our spiritual heritage.',
 E'Our community has come together to support this monumental project that will enhance the worship experience for all members. The Grand Mosque renovation project represents a significant milestone in our community\'s development.\n\nThe renovation will include:\n• Modern climate control systems for year-round comfort\n• Upgraded audio and lighting systems\n• Restoration of traditional architectural elements\n• Expanded prayer areas to accommodate more worshippers\n• Improved accessibility features for elderly and disabled members\n• Beautiful landscaping around the mosque grounds\n\nThis project has been in planning for over two years, with extensive consultations with community members, Islamic scholars, and architectural experts. We are committed to preserving the spiritual essence and historical significance of our beloved mosque while incorporating modern amenities that will serve our growing community for generations to come.\n\nThe estimated timeline for completion is 18 months, and we invite all community members to participate in this blessed endeavor through donations, volunteering, and prayers for its successful completion.',
 'Announcements',
 'Admin Team',
 'Official community administration',
 'March 15, 2025',
 '5 min read',
 234,
 45),

(2,
 'Community Iftar - Join Us This Ramadan',
 'إفطار جماعي - انضم إلينا هذا رمضان',
 'Daily community Iftar throughout Ramadan. All members and families are welcome to break fast together in unity and brotherhood.',
 E'We invite all community members to join us for daily Iftar gatherings during the blessed month of Ramadan. This is a wonderful opportunity to strengthen our bonds of brotherhood and sisterhood while sharing the spiritual experience of breaking fast together.\n\nSchedule and Details:\n• Daily Iftar from Maghrib prayer\n• Delicious traditional meals prepared by community volunteers\n• Special programs for children during Taraweeh\n• Weekend lectures by visiting scholars\n• Charity drive for those in need\n\nEveryone is welcome, and we especially encourage families to attend. There is no cost to participate, though donations are welcome to help cover expenses and support our charitable initiatives.\n\nPlease register in advance so we can prepare adequate food and seating arrangements. Registration forms are available at the mosque office or online through our community portal.\n\nJoin us in making this Ramadan a truly memorable and spiritually enriching experience for our entire community.',
 'Events',
 'Events Committee',
 'Organizing community events and gatherings',
 'March 12, 2025',
 '3 min read',
 189,
 32),

(3,
 'Youth Islamic Studies Program Success',
 'نجاح برنامج الدراسات الإسلامية للشباب',
 'Our youth program has successfully completed its first semester with over 150 students learning Quran, Arabic, and Islamic studies.',
 E'The inaugural semester of our Youth Islamic Studies Program has concluded with remarkable success. Over 150 students participated in comprehensive courses covering Quran recitation, Arabic language, Islamic history, and moral education.\n\nProgram Highlights:\n• 95% attendance rate throughout the semester\n• 40 students memorized full Surahs\n• 60 students achieved proficiency in Arabic reading\n• Weekly interactive sessions with Islamic scholars\n• Community service projects integrated into curriculum\n\nOur dedicated teachers have worked tirelessly to create an engaging and enriching learning environment. Students ranged from ages 8 to 18, with classes tailored to different age groups and skill levels.\n\nThe graduation ceremony was a joyous occasion, with students demonstrating their knowledge through Quran recitation, Arabic presentations, and Islamic quiz competitions. Parents expressed overwhelming satisfaction with their children\'s progress and enthusiasm for continuing their Islamic education.\n\nRegistration for the next semester begins April 1st. We are expanding our program to include advanced courses in Tafsir and Islamic jurisprudence for older students.',
 'Education',
 'Education Team',
 'Dedicated to Islamic education excellence',
 'March 8, 2025',
 '4 min read',
 312,
 67),

(4,
 'Tree Planting Initiative Results',
 'نتائج مبادرة زراعة الأشجار',
 '500+ trees planted around our community in the environment beautification project. Thank you to all volunteers!',
 E'Our community came together last weekend to plant over 500 trees as part of our environment beautification initiative. This remarkable achievement demonstrates our commitment to environmental stewardship and creating a greener, more beautiful community for future generations.\n\nThe tree planting event saw participation from:\n• Over 200 volunteers of all ages\n• Local schools and youth groups\n• Environmental organizations\n• Community families\n\nTypes of trees planted include shade trees, fruit trees, and flowering species native to our region. Each tree was carefully selected for its environmental benefits and aesthetic appeal.\n\nVolunteers worked in teams, with experienced arborists providing guidance on proper planting techniques. Children enthusiastically participated, learning about the importance of trees in Islam and environmental conservation.\n\nThis initiative is part of our larger environmental beautification project, which also includes creating public gardens, maintaining green spaces, and promoting sustainable practices within our community.\n\nWe plan to organize quarterly tree planting events and encourage all members to participate in these blessed activities.',
 'Community',
 'Community Team',
 'Building stronger community connections',
 'March 8, 2025',
 '2 min read',
 276,
 41),

(5,
 'New Agricultural Tools Distributed',
 'توزيع الأدوات الزراعية الجديدة',
 'Modern farming equipment distributed to local farmers as part of the Tool Baye Agriculture Project.',
 E'In partnership with Tool Baye, we successfully distributed modern agricultural equipment to support our farming community. This initiative aims to enhance agricultural productivity and improve the livelihoods of local farmers.\n\nEquipment distributed includes:\n• Modern plowing tools\n• Irrigation systems\n• Quality seeds and fertilizers\n• Harvesting equipment\n• Training manuals and guides\n\nOver 50 farming families received these tools during a special distribution ceremony. Agricultural experts were present to provide training on the proper use and maintenance of the equipment.\n\nThe Tool Baye Agriculture Project represents our commitment to supporting sustainable farming practices and ensuring food security for our community. This is the first phase of a comprehensive agricultural development program that will continue throughout the year.\n\nFarmers expressed gratitude for the support and are excited to implement modern techniques that will increase yields while preserving traditional farming wisdom passed down through generations.\n\nWe will continue monitoring the project\'s impact and providing ongoing support to ensure its success.',
 'Projects',
 'Projects Team',
 'Managing community development projects',
 'March 1, 2025',
 '3 min read',
 198,
 28);
